# Generated by Django 4.0.5 on 2022-10-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_event_client_alter_event_contract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('finished', 'finished')], default='in_progress', max_length=12),
        ),
    ]
